replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ''
production:
  database:
    host: ''
    port: ''
    username: ''
    password: ''
    databaseBom: ''
    databaseConfig: ''
    timezone: +09:00
    dialect: ''
  keycloak:
    clientId: ''
    clientSecret: ''
    redirectUri: ''
    adminUsername: ''
    adminPassword: ''
    realm: ''
  stibee:
    listID: ''
    apiKey: ''
  smtp:
    user: ''
    password: ''
  google:
    clientId: ''
    clientSecret: ''
    loginRedirectUri: ''
  redirectUri:
    main: ''
  mailer:
    verificationPage: ''
    pwdResetUrl: ''
backend:
  enabled: true
  imageName: vetec/plate-auth-backend
  tag: '''e9be4e9'''
  port: 3723
  targetPort: 3723
  replicas: 1
frontend:
  enabled: true
  imageName: vetec/plate-auth-frontend
  tag: aff5db7
  port: 3750
  targetPort: 3750
  replicas: 1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ''
  hostname: ''
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
