{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-frontend-service
spec:
  selector:
    app: {{ .Release.Name }}-app-frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.targetPort }}
  type: ClusterIP
{{- end}}